// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ShirtSize$Collections = require("./ShirtSize.bs.js");

var myShirt = /* XLarge */{
  _0: 1
};

var myPrice = ShirtSize$Collections.price(myShirt);

console.log("Price: ", ShirtSize$Collections.toFixed(myPrice, 2));

exports.myShirt = myShirt;
exports.myPrice = myPrice;
/* myPrice Not a pure module */
