// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

function getValue(element) {
  var __x = Belt_Option.map(element, (function (prim) {
          return prim;
        }));
  return Belt_Option.map(__x, (function (prim) {
                return prim.value;
              }));
}

function toInt(s) {
  var result;
  try {
    result = Caml_format.caml_int_of_string(s);
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === "Failure") {
      if (exn._1 === "int_of_string") {
        return ;
      }
      throw exn;
    }
    throw exn;
  }
  return result;
}

function toFloat(s) {
  var result;
  try {
    result = Caml_format.caml_float_of_string(s);
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === "Failure") {
      if (exn._1 === "float_of_string") {
        return ;
      }
      throw exn;
    }
    throw exn;
  }
  return result;
}

function payment(principal, apr, years, param) {
  var r = apr / 12.0 / 100.0;
  var n = Math.imul(years, 12);
  var powerTerm = Math.pow(1.0 + r, n);
  return principal * (r * powerTerm) / (powerTerm - 1.0);
}

function calculatePayments(param) {
  console.log("in calculatePayments!");
  var p = Belt_Option.flatMap(getValue(Caml_option.nullable_to_opt(document.getElementById("principal"))), toFloat);
  var a = Belt_Option.flatMap(getValue(Caml_option.nullable_to_opt(document.getElementById("apr"))), toFloat);
  var y = Belt_Option.flatMap(getValue(Caml_option.nullable_to_opt(document.getElementById("years"))), toInt);
  var r = p !== undefined ? (
      a !== undefined ? (
          y !== undefined ? payment(p, a, y, undefined) : -1.0
        ) : -1.0
    ) : -1.0;
  var s = r.toString();
  var __x = document.getElementById("payment");
  Belt_Option.map((__x == null) ? undefined : Caml_option.some(__x), (function (__x) {
          __x.innerText = s;
          
        }));
  
}

function addOnChange(dst) {
  console.log("in addOnChange");
  if (dst !== undefined) {
    Caml_option.valFromOption(dst).addEventListener("onchange", calculatePayments);
    return ;
  }
  
}

var principal = document.getElementById("principal");

var principal$1 = (principal == null) ? undefined : Caml_option.some(principal);

var apr = document.getElementById("apr");

var apr$1 = (apr == null) ? undefined : Caml_option.some(apr);

var years = document.getElementById("years");

var years$1 = (years == null) ? undefined : Caml_option.some(years);

var button = document.getElementById("docalc");

console.log("here");

addOnChange(principal$1);

addOnChange(apr$1);

addOnChange(years$1);

if (!(button == null)) {
  button.addEventListener("click", calculatePayments);
}

var D;

var Doc;

var Elem;

var button$1 = (button == null) ? undefined : Caml_option.some(button);

exports.D = D;
exports.Doc = Doc;
exports.Elem = Elem;
exports.getValue = getValue;
exports.toInt = toInt;
exports.toFloat = toFloat;
exports.payment = payment;
exports.calculatePayments = calculatePayments;
exports.addOnChange = addOnChange;
exports.principal = principal$1;
exports.apr = apr$1;
exports.years = years$1;
exports.button = button$1;
/* principal Not a pure module */
